cuberacer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('pages.urls')),
    url(r'^timer/', include('timer.urls')),
    url(r'^admin/', admin.site.urls),
]

pages/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout

from . import views

app_name = 'pages'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', login, {'template_name': 'pages/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'pages/logout.html', 'next_page': '/'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

timer/urls.py
from django.conf.urls import url

from . import views

app_name = 'timer'
urlpatterns = [
    url(r'^solo/$', views.solo, name='solo'),
    url(r'multi/$', views.multi, name='multi'),
]

pages/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    join_date = models.DateField(auto_now_add=True)
    website = models.URLField(default='')
    description = models.CharField(default='', max_length=200)

    def __str__(self):
        return self.user


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

timer/models.py
from django.db import models
from django.contrib.auth.models import User


class Session(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    puzzle = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.user}: {self.date}'


class Solve(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    time = models.DecimalField(decimal_places=3, max_digits=7)

    def __str__(self):
        return f'{self.session.puzzle}: {self.time}'

pages/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.safestring import mark_safe

red_asterisk = mark_safe(' <font color="red">*</font>')


class RegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=20, help_text='20 characters or fewer. Letters, digits and @/./+/-/_ only.')
    email_address = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2',
            'email_address',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email_address = self.cleaned_data['email_address']

        if commit:
            user.save()

        return user

pages/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from . import forms


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        form = forms.RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'])
            login(request, new_user)
            return redirect('/')
        else:
            args = {'form': form}
            return render(request, 'pages/register.html', args)
    else:
        form = forms.RegistrationForm()
        args = {'form': form}
        return render(request, 'pages/register.html', args)


@login_required
def index(request):
    return render(request, 'pages/index.html')

timer/views.py
from django.http import HttpResponse
from django.shortcuts import render


def solo(request):
    if request.method == 'POST':
        print(request.POST.get('value1'))
        return HttpResponse(status=201)
    else:
        return render(request, 'timer/solo.html')


def multi(request):
    return render(request, 'timer/multi.html')

pages/templates/base.html
<html>

<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script   src="https://code.jquery.com/jquery-3.2.1.min.js"
              integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    {% block head %}
    <title>Base</title>
    {% endblock %}
</head>

<body>
<br>
<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'pages:index' %}">CubeRacer</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'timer:solo' %}">Solo</a></li>
                    <li><a href="{% url 'timer:multi' %}">Multi</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'pages:logout' %}">Logout</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'pages:login' %}">Login</a></li>
                    <li><a href="{% url 'pages:register' %}">Register</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
</div>
{% block body %}
<h1>Base</h1>
{% endblock %}
</body>

</html>

pages/templates/pages/index.html
{% extends 'base.html' %}

{% block head %}
<title>CubeRacer</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Welcome, {{ user }}</h1>
</div>
{% endblock %}

pages/templates/pages/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        Please login or <a href="{% url 'pages:register' %}">register</a> to continue.
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

pages/templates/pages/logout.html
{% extends 'base.html' %}

{% block head %}
<title>Logged out</title>
{% endblock %}

{% block body %}
<div class="container">
    <p>You have been successfully logged out.</p>
</div>
{% endblock %}

pages/templates/pages/register.html
{% extends 'base.html' %}

{% block head %}
<title>Register</title>
{% endblock %}

{% block body %}

<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

pages/templates/timer/login.html
{% block body %}
<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

timer/templates/timer/multi.html
{% extends 'base.html' %}

{% block head %}
<title>Multi</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Multi</h1>
</div>
{% endblock %}

timer/templates/timer/solo.html
{% extends 'base.html' %}

{% block head %}
<title>Solo</title>
<script type="text/javascript">
    function submitScores() {
        $.post('/timer/solo/', {value1: 'Value #1', value2: 'Value #2', csrfmiddlewaretoken: '{{ csrf_token }}'});
    }
</script>
{% load static %}
<script type="text/javascript" src="{% static 'timer/timer.js' %}"></script>
{% endblock %}

{% block body %}
<div class="container">
    <span id="time">0</span>
    <br>
    <button type="button" onclick="submitScores()">Submit</button>
</div>
{% endblock %}